name: Lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  lint:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Luacheck Linter
        uses: lunarmodules/luacheck@v1
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5
