name: Lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  lint:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
      - uses: Jayrgo/luacheck-action@v1
        with:
          files: '.'
      - uses: wagoid/commitlint-github-action@v5
